### ISSUE TITLE
Blackwidow Chroma V2, keys not responding.

### ISSUE THREAD

**Issue by kierun** [moozhub/yum-repo-mooz#1]
I installed the `openrazer-2.3.0` and `polychromatic-0.3.11.1` and plugged in the new keyboard. During bios the keyboard works but as soon as Linux (CentOS7) boots, none of the keys on the key board do anything (press key, nothing happens). The colours on the keyboard work just fine and I am able to switch theme using `polychromatic-controll` just fine.

*Any idea how I can get this to work?*

Here is some debugging information.

```
; uname -a     
Linux serval.isotek.co.uk 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
; dmesg | ag -i razer
[    2.103400] usb 2-1.6: Product: Razer BlackWidow Chroma V2
[    2.103401] usb 2-1.6: Manufacturer: Razer
[    2.104150] input: Razer Razer BlackWidow Chroma V2 as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/input/input5
[    2.154354] hid-generic 0003:1532:0221.0003: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer BlackWidow Chroma V2] on usb-0000:00:1d.0-1.6/input0
[    2.155163] input: Razer Razer BlackWidow Chroma V2 as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.1/input/input6
[    2.206258] hid-generic 0003:1532:0221.0004: input,hidraw3: USB HID v1.11 Keyboard [Razer Razer BlackWidow Chroma V2] on usb-0000:00:1d.0-1.6/input1
[    2.206914] input: Razer Razer BlackWidow Chroma V2 as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.2/input/input7
[    2.207010] hid-generic 0003:1532:0221.0005: input,hidraw4: USB HID v1.11 Mouse [Razer Razer BlackWidow Chroma V2] on usb-0000:00:1d.0-1.6/input2
[    3.644772] razerkbd: loading out-of-tree module taints kernel.
[    3.645663] razerkbd: module verification failed: signature and/or required key missing - tainting kernel
[    3.771283] input: Razer Razer BlackWidow Chroma V2 as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/input/input11
[    3.778643] input: Razer Razer BlackWidow Chroma V2 as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.2/input/input12
[    3.810552] razerkbd 0003:1532:0221.0003: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer BlackWidow Chroma V2] on usb-0000:00:1d.0-1.6/input0
[    3.810689] razerkbd 0003:1532:0221.0005: input,hidraw3: USB HID v1.11 Mouse [Razer Razer BlackWidow Chroma V2] on usb-0000:00:1d.0-1.6/input2
[    3.814567] input: Razer Razer BlackWidow Chroma V2 as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.1/input/input16
[    3.814733] razerkbd 0003:1532:0221.0004: input,hidraw4: USB HID v1.11 Keyboard [Razer Razer BlackWidow Chroma V2] on usb-0000:00:1d.0-1.6/input1
```
[razer.log](https://github.com/moozhub/yum-repo-mooz/files/2101380/razer.log)

**Comment by moozhub** [comment]
Some other users were having the same issue with this keyboard I believe. However since the driver is being loaded and is recognizing your keyboard, it's not a packaging problem and I suggest reporting the problem to the developer of the driver at https://github.com/openrazer/openrazer

First what you can try though is make sure you're upgraded to the newest CentOS 7 release `sudo yum update` ... and afterwards following a reboot if the kernel was updated reinstall the driver `sudo dkms install openrazer-driver/1.0.0`. This will automatically reinstall the driver into the kernel tree using dkms.

**Comment by kierun** [comment]
Openrazer is where I opened the bug in the first place. They bounced me here. ☺

Yes, I am on the latest CentOS 7. I rebooted a dozen times or so, thus I am pretty sure that the driver is loaded. I can use chromatic to change the colours so clearly something is working. I tried the keyboard on a spare centos laptop and it works there… 

I am confused.

**Comment by moozhub** [comment]
Does the keyboard work when using it outside of Xorg? eg. booting directly into a single or multi-user target? What window environment are you using (gnome3, kde, mate)? To test this you may have to start the daemon and / or load the module manually.

Problem is I don't have this keyboard... I know that there was another user that had this issue, but not sure if they were able to correct it. The only keyboard device that I have that is compatible is the BlackWidow X Chroma, and I haven't had any issues with it, not really sure why there would be a issue with yours saying it's also compatible.. 

Do you have SELinux enabled? I have SELinux enabled on mine, but just wondering if you have some files with incorrect attributes. If it is enabled, `/var/log/audit.log` may provide some information, or just disable it completely and try.

**Comment by kierun** [comment]
Keyboard does not work in console either, just works in BIOS. I run `awesome` but it does not work in gdm as well so I guess that no other window managers will work. I did try with and without SELinux and nothing changed.

I think the machine itself is too old. It's about 5/6 years old…

Meh, I guess I have an expensive door stop now. Wife might be able to use it in her new job so not a total loss.

**Comment by kierun** [comment]
I am officially giving up …  

Thank you for your efforts and help.

**Comment by moozhub** [comment]
Yep.. sorry. One last thing you can try is updating your kernel to kernel-ml from the [ELRepo](http://elrepo.org/tiki/kernel-ml) since it could be a issue with the kernel. The dmesg information you provide doesn't really indicate this, but it's worth a try if you're up for it.

**Comment by moozhub** [comment]
@kierun 

Another user was having a issue with a mouse not working, they found that they had to run `/usr/bin/hid-recorder` after the device was plugged in, not sure if or why this would need to be ran for each razer device.. but if you find some time would you be able to try loading the module and executing the above command afterward?

If it works I may end up having to write a patch for the udev rules that are currently being installed.

Take a look at [Issue #363](https://github.com/openrazer/openrazer/issues/363#issuecomment-327668169) to see what it is the other user was running.

This utility is in the `hid-replay` package.

**Comment by kierun** [comment]
I shall give that a go. It might be a few days as I won't be back in the office till Thursday.

Thank you!

**Comment by kierun** [comment]
**SUCCESS!!!**

Even without the driver loaded, just running `hid-recorder` as root and then killing it made it work.

Thank you kind sire!

**Comment by moozhub** [comment]
@kierun can you try to run `udevadm test <device-path>` after you plug in the device and before running hid-recorder? I'm curious to know what it's doing when parsing the udev rules, it may be failing to find the device for some strange reason. Not sure which device path to use for the test, perhaps all that were written to dmesg in your above log. 

Also after plugging in the keyboard, can you give me the output of `ls -l /dev/input`? Wondering if it's a permissions issue.

**Comment by kierun** [comment]
Here you go.

[razer-after.log](https://github.com/moozhub/yum-repo-mooz/files/2174927/razer-after.log)
[razer-before.log](https://github.com/moozhub/yum-repo-mooz/files/2174928/razer-before.log)

```
; ls -l /dev/input
total 0
0 drwxr-xr-x. 2 root root       200 Jul  9 07:54 by-id/
0 drwxr-xr-x. 2 root root       280 Jul  9 07:54 by-path/
0 crw-rw----. 1 root input   13, 64 Jul  6 12:57 event0
0 crw-rw----. 1 root input   13, 65 Jul  6 12:57 event1
0 crw-rw----. 1 root input   13, 66 Jul  6 12:57 event2
0 crw-rw----. 1 root input   13, 67 Jul  6 12:57 event3
0 crw-rw----. 1 root plugdev 13, 68 Jul  9 07:54 event4
0 crw-rw----. 1 root plugdev 13, 69 Jul  9 07:54 event5
0 crw-rw----. 1 root input   13, 70 Jul  6 12:57 event6
0 crw-rw----. 1 root input   13, 71 Jul  6 12:57 event7
0 crw-rw----. 1 root input   13, 72 Jul  6 12:57 event8
0 crw-rw----. 1 root input   13, 73 Jul  6 12:57 event9
0 crw-rw----. 1 root input   13, 74 Jul  6 12:57 event10
0 crw-rw----. 1 root input   13, 75 Jul  6 12:57 event11
0 crw-rw----. 1 root input   13, 76 Jul  6 12:57 event12
0 crw-rw----. 1 root plugdev 13, 77 Jul  9 07:54 event13
0 crw-rw----. 1 root input   13, 78 Jul  6 12:57 event14
0 crw-rw----. 1 root input   13, 79 Jul  6 12:57 event15
0 crw-rw----. 1 root input   13, 80 Jul  6 12:57 event16
0 crw-rw----. 1 root input   13, 81 Jul  6 12:57 event17
0 crw-rw----. 1 root input   13, 82 Jul  6 12:57 event18
0 crw-rw----. 1 root input   13, 63 Jul  6 12:57 mice
0 crw-rw----. 1 root plugdev 13, 32 Jul  9 07:54 mouse0
0 crw-rw----. 1 root input   13, 33 Jul  6 12:57 mouse1
0 crw-rw----. 1 root input   13, 34 Jul  6 12:57 mouse2
```

and 

```
; ls -lZ /dev/input  
total 0
drwxr-xr-x. root root    system_u:object_r:device_t:s0    by-id/
drwxr-xr-x. root root    system_u:object_r:device_t:s0    by-path/
crw-rw----. root input   system_u:object_r:event_device_t:s0 event0
crw-rw----. root input   system_u:object_r:event_device_t:s0 event1
crw-rw----. root input   system_u:object_r:event_device_t:s0 event2
crw-rw----. root input   system_u:object_r:event_device_t:s0 event3
crw-rw----. root plugdev system_u:object_r:event_device_t:s0 event4
crw-rw----. root plugdev system_u:object_r:event_device_t:s0 event5
crw-rw----. root input   system_u:object_r:event_device_t:s0 event6
crw-rw----. root input   system_u:object_r:event_device_t:s0 event7
crw-rw----. root input   system_u:object_r:event_device_t:s0 event8
crw-rw----. root input   system_u:object_r:event_device_t:s0 event9
crw-rw----. root input   system_u:object_r:event_device_t:s0 event10
crw-rw----. root input   system_u:object_r:event_device_t:s0 event11
crw-rw----. root input   system_u:object_r:event_device_t:s0 event12
crw-rw----. root plugdev system_u:object_r:event_device_t:s0 event13
crw-rw----. root input   system_u:object_r:event_device_t:s0 event14
crw-rw----. root input   system_u:object_r:event_device_t:s0 event15
crw-rw----. root input   system_u:object_r:event_device_t:s0 event16
crw-rw----. root input   system_u:object_r:event_device_t:s0 event17
crw-rw----. root input   system_u:object_r:event_device_t:s0 event18
crw-rw----. root input   system_u:object_r:mouse_device_t:s0 mice
crw-rw----. root plugdev system_u:object_r:mouse_device_t:s0 mouse0
crw-rw----. root input   system_u:object_r:mouse_device_t:s0 mouse1
crw-rw----. root input   system_u:object_r:mouse_device_t:s0 mouse2
```

Just in case

**Comment by moozhub** [comment]
It looks like there's some lingo in the driver source about probing keyboards as a mouse device, I just noticed in your dmesg that razerkbd is showing it as a mouse device after it's initial recognition that it's a keybard ...not exactly sure if that's what's causing this but I'll have to ask the developer about it...

In the meantime, are you using any other razer devices other than the keyboard? What are you using for a mouse?

**Comment by kierun** [comment]
> It looks like there's some lingo in the driver source about probing keyboards as a mouse device […]

I did notice that and cannot fathom why that would be… 

> In the meantime, are you using any other razer devices other than the keyboard? 

No, just the keyboard.

I do have my old logitech keyboard plugged in as well. That runs native without an issue. No drivers installed, apart from the vanilla ones.

> What are you using for a mouse?

It is a logitech one:

```
; dmesg | ag -i logitech                                                        
[    1.297105] usb 2-1.3: Manufacturer: Logitech                                
[    1.300344] input: Logitech USB Multimedia Keyboard as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3/2-1.3:1.0/input/input6                                
[    1.351046] hid-generic 0003:046D:C317.0004: input,hidraw3: USB HID v1.10 Keyboard [Logitech USB Multimedia Keyboard] on usb-0000:00:1d.0-1.3/input0         
[    1.356322] input: Logitech USB Multimedia Keyboard as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3/2-1.3:1.1/input/input7                                
[    1.406955] hid-generic 0003:046D:C317.0005: input,hidraw4: USB HID v1.10 Device [Logitech USB Multimedia Keyboard] on usb-0000:00:1d.0-1.3/input1           
[    1.578356] usb 2-1.5: Manufacturer: Logitech                                
[    1.583162] input: Logitech USB Laser Mouse as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.5/2-1.5:1.0/input/input8                                        
[    1.583332] hid-generic 0003:046D:C069.0006: input,hidraw5: USB HID v1.10 Mouse [Logitech USB Laser Mouse] on usb-0000:00:1d.0-1.5/input0 
```

**Comment by moozhub** [comment]
Haven't had a whole lot of time to take a look...have you tried updating to the latest version that I have in the repo? Curious as to the output of `dkms status -m openrazer-driver -v 2.3.1` for you is, `dkms status -m openrazer-driver -v 1.0.0` if you haven't updated yet.

**Comment by kierun** [comment]
This is what I am getting:

```
; dkms status -m openrazer-driver -v 2.3.1
; dkms status -m openrazer-driver -v 1.0.0
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/openrazer-driver/1.0.0/source/dkms.conf does not exist.
; rpm -qa | ag -i openrazer  
openrazer-meta-2.3.1-1.el7.noarch
```

**Comment by moozhub** [comment]
The status should be returning something like this:

` # dkms status -m openrazer-driver -v 2.3.1`
` openrazer-driver, 2.3.1, 4.16.0-1.el7.elrepo.x86_64, x86_64: installed (original_module exists)`

If it's not, then the RPM may not be installing module and I'll have to look into that.. Can you do `sudo dkms --force install openrazer-driver/2.3.1` followed by another status? Because of the recent change to the dkms version in 2.3.1 it may take a bit of tinkering to get it to show as installed.

**Comment by kierun** [comment]
This looks better:

```
; sudo dkms --force install openrazer-driver/2.3.1                             

Creating symlink /var/lib/dkms/openrazer-driver/2.3.1/source ->                
                 /usr/src/openrazer-driver-2.3.1                               

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...                   

Building module:
cleaning build area...
KERNELDIR=/lib/modules/3.10.0-862.9.1.el7.x86_64/build make driver....         
cleaning build area...

DKMS: build completed.

razerkbd.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel                              
 - Installation
   - Installing to /lib/modules/3.10.0-862.9.1.el7.x86_64/extra/               

razermouse.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel                              
 - Installation
   - Installing to /lib/modules/3.10.0-862.9.1.el7.x86_64/extra/               

razerfirefly.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel                              
 - Installation
   - Installing to /lib/modules/3.10.0-862.9.1.el7.x86_64/extra/               

razerkraken.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel                              
 - Installation
   - Installing to /lib/modules/3.10.0-862.9.1.el7.x86_64/extra/               

razermug.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel                              
 - Installation
   - Installing to /lib/modules/3.10.0-862.9.1.el7.x86_64/extra/               

razercore.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel                              
 - Installation
   - Installing to /lib/modules/3.10.0-862.9.1.el7.x86_64/extra/               
Adding any weak-modules

depmod...

DKMS: install completed.
; dkms status -m openrazer-driver -v 2.3.1                                     
openrazer-driver, 2.3.1, 3.10.0-862.9.1.el7.x86_64, x86_64: installed  
```

**Comment by moozhub** [comment]
Take a look at #3 for a few possible workarounds.. Closing this for now.

**Comment by kierun** [comment]
Updating to `kernel-ml` did the trick. Thank you.
