### ISSUE TITLE
Razer mouse not working after openrazer install on RHEL/Centos 7

### ISSUE THREAD

**Issue by oilian** [moozhub/yum-repo-mooz#2]
Hi Mooz,

thanks for packaging the openrazer daemon for RHEL/Centos. Quick question; did you ever found a solution for https://github.com/openrazer/openrazer/issues/363

I installed the driver and everything works fine, except I have to run hid-recorder after each start (or unplug/replug) of the mouse.

Any idea what this could be?

Razer Naga Hex v2

Thanks
Oliver

**Comment by moozhub** [comment]
I'm closing this since there's quite a bit of communication going on in another ticket that's seemingly related to this.
