### ISSUE TITLE
Can't install 2.4.0 in Centos 7

### ISSUE THREAD

**Issue by alh61** [moozhub/yum-repo-mooz#4]
missing dependicies during yum install:
--> Afsluttede afhængighedssøgningen
Fejl: Pakke: razer-daemon-2.4.0-1.el7.noarch (mooz-yum-repo-mooz)
          Kræver: python34-dbus
Fejl: Pakke: python3-razer-2.4.0-1.el7.noarch (mooz-yum-repo-mooz)
          Kræver: python34-dbus
Fejl: Pakke: razer-daemon-2.4.0-1.el7.noarch (mooz-yum-repo-mooz)
          Kræver: python34-setproctitle
 Du kunne prøve at bruge --skip-broken til at arbejde udenom problemet
 Du kan prøve at køre: rpm -Va --nofiles --nodigest

(sorry about the Danish texts)

**Comment by alh61** [comment]
@moozhub  Any ideas ?

**Comment by moozhub** [comment]
It appears that python34-dbus was removed from the EPEL repo for some reason. I will look at getting a fix in place..

**Comment by moozhub** [comment]
I'll have to build a new openrazer package for the python36 migration, and may as well update openrazer to 2.5.0 while I'm at it... I'll let you know when you can try again

**Comment by moozhub** [comment]
@alh61 new packages are in the repo, let me know if you're having any other issues there might be another package that needs to be rebuilt, but looks like everything wants to install fine now.

**Comment by alh61** [comment]
Thx moozhub for the new files. Everything installs without problems; but trying to run polychromatic ends with:
~>polychromatic-controller
Failed to import modules for daemon.
Exception: No module named 'gi'
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 68, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

I don't know what to do here.

I'm using kernel 4.19.40 from Centos experimental repo

**Comment by moozhub** [comment]
OK I'm pretty sure I got this working again. You can try updating the packages again, but if it doesn't work and polychromatic indicates that it's unable to find the openrazer module you're going to have to reinstall the packages that were installed..

`sudo yum remove python36-dbus python36-setproctitle python3-gobject xautomation python3-gobject-base python3-daemonize polychromatic openrazer-meta razer\*`

`sudo yum install polychromatic`

Closing this one unless you find other issues..

**Comment by alh61** [comment]
Thx again moozhub - that actually did the trick, even though I had removed it and reinstalled it before. 
I guess the trick was, that your command removed python3-gobject - and the install now included python36-gobject instead.

Everything is working again now :-)
