### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by nl20121974** [moozhub/yum-repo-mooz#5]
Hi bro,

this link does not work anymore : 

https://copr-be.cloud.fedoraproject.org/results/mooz/yum-repo-mooz/epel-7-x86_64/repodata/repomd.xml

with the following error : 

...« mooz-yum-repo-mooz » : Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

It seems it's now at : 

https://copr-be.cloud.fedoraproject.org/results/mooz/yum-repo-mooz/fedora-34-x86_64/repodata/repomd.xml

Thank you for the hard work

Regards, Nicolas

**Comment by moozhub** [comment]
@nl20121974 Sorry about that, it should be back up. This repo is sort of defunct but I'd imagine it should be working, but just be aware that some of the packages are out of date. Let me know if you have any issues I'll see about taking some time to look at them.
